INSERT INTO CAR (ID, VERSION, AGE, AVAILABLE, CAR_TYPE, DISTANCE, PRICE_HOUR) VALUES (1, 0, 1, TRUE, 'BMW', 10, 1000);
INSERT INTO CAR (ID, VERSION, AGE, AVAILABLE, CAR_TYPE, DISTANCE, PRICE_HOUR) VALUES (2, 0, 1, TRUE, 'Mercedes', 10, 1000);
INSERT INTO CAR (ID, VERSION, AGE, AVAILABLE, CAR_TYPE, DISTANCE, PRICE_HOUR) VALUES (3, 0, 1, TRUE, 'Audi', 10, 1000);
INSERT INTO CAR (ID, VERSION, AGE, AVAILABLE, CAR_TYPE, DISTANCE, PRICE_HOUR) VALUES (4, 0, 1, TRUE, 'BMW', 10, 1000);
