INSERT INTO CAR (ID, VERSION, AGE, AVAILABLE, CAR_TYPE, DISTANCE, PRICE_HOUR) VALUES (1, 0, 42, TRUE, 'Lada', 1001, 3000);
INSERT INTO CAR (ID, VERSION, AGE, AVAILABLE, CAR_TYPE, DISTANCE, PRICE_HOUR) VALUES (2, 0, 28, TRUE, 'Suzuki Siwft', 100, 2000);
INSERT INTO CAR (ID, VERSION, AGE, AVAILABLE, CAR_TYPE, DISTANCE, PRICE_HOUR) VALUES (3, 0, 20, TRUE, 'Opel Astra', 100000, 1000);
